# Form implementation generated from reading ui file 'RegistrarModeloWidget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegistrarModeloWidget(object):
    def setupUi(self, RegistrarModeloWidget):
        RegistrarModeloWidget.setObjectName("RegistrarModeloWidget")
        RegistrarModeloWidget.resize(1131, 722)
        RegistrarModeloWidget.setStyleSheet("background-color: rgb(214, 198, 156);")
        self.frame_3 = QtWidgets.QFrame(parent=RegistrarModeloWidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1131, 101))
        self.frame_3.setStyleSheet("background-color: rgb(153, 148, 137);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.registrarModelo_Title = QtWidgets.QLabel(parent=self.frame_3)
        self.registrarModelo_Title.setGeometry(QtCore.QRect(280, 10, 671, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.registrarModelo_Title.setFont(font)
        self.registrarModelo_Title.setObjectName("registrarModelo_Title")
        self.frame = QtWidgets.QFrame(parent=RegistrarModeloWidget)
        self.frame.setGeometry(QtCore.QRect(0, 130, 1131, 571))
        self.frame.setStyleSheet("background-color: rgb(176, 155, 101);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_12 = QtWidgets.QFrame(parent=self.frame)
        self.frame_12.setGeometry(QtCore.QRect(200, 50, 731, 431))
        self.frame_12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_13.setGeometry(QtCore.QRect(180, 40, 441, 91))
        self.frame_13.setStyleSheet("background-color: rgb(176, 155, 101);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.ingreseModeloLbl = QtWidgets.QLabel(parent=self.frame_13)
        self.ingreseModeloLbl.setGeometry(QtCore.QRect(10, 0, 441, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.ingreseModeloLbl.setFont(font)
        self.ingreseModeloLbl.setObjectName("ingreseModeloLbl")
        self.IngresarModelo_lineEdit = QtWidgets.QLineEdit(parent=self.frame_12)
        self.IngresarModelo_lineEdit.setGeometry(QtCore.QRect(270, 170, 271, 51))
        self.IngresarModelo_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.IngresarModelo_lineEdit.setObjectName("IngresarModelo_lineEdit")
        self.IngresarModelo_Btn = QtWidgets.QPushButton(parent=self.frame_12)
        self.IngresarModelo_Btn.setGeometry(QtCore.QRect(290, 260, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.IngresarModelo_Btn.setFont(font)
        self.IngresarModelo_Btn.setStyleSheet("background-color: rgb(229, 190, 88);")
        self.IngresarModelo_Btn.setObjectName("IngresarModelo_Btn")
        self.frame_19 = QtWidgets.QFrame(parent=self.frame)
        self.frame_19.setGeometry(QtCore.QRect(950, 480, 181, 91))
        self.frame_19.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.CancelarRegistroModelo_Btn = QtWidgets.QPushButton(parent=self.frame_19)
        self.CancelarRegistroModelo_Btn.setGeometry(QtCore.QRect(20, 10, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.CancelarRegistroModelo_Btn.setFont(font)
        self.CancelarRegistroModelo_Btn.setStyleSheet("background-color: rgb(214, 53, 26);")
        self.CancelarRegistroModelo_Btn.setObjectName("CancelarRegistroModelo_Btn")

        self.retranslateUi(RegistrarModeloWidget)
        self.IngresarModelo_Btn.clicked.connect(RegistrarModeloWidget.confirmarModelo) # type: ignore
        self.CancelarRegistroModelo_Btn.clicked.connect(RegistrarModeloWidget.cerrarRegistrarModeloWidget) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RegistrarModeloWidget)

    def retranslateUi(self, RegistrarModeloWidget):
        _translate = QtCore.QCoreApplication.translate
        RegistrarModeloWidget.setWindowTitle(_translate("RegistrarModeloWidget", "Form"))
        self.registrarModelo_Title.setText(_translate("RegistrarModeloWidget", "Registrar Nuevo Modelo"))
        self.ingreseModeloLbl.setText(_translate("RegistrarModeloWidget", "Ingrese Nuevo Modelo"))
        self.IngresarModelo_Btn.setText(_translate("RegistrarModeloWidget", "Ingresar \n"
"Modelo"))
        self.CancelarRegistroModelo_Btn.setText(_translate("RegistrarModeloWidget", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrarModeloWidget = QtWidgets.QWidget()
    ui = Ui_RegistrarModeloWidget()
    ui.setupUi(RegistrarModeloWidget)
    RegistrarModeloWidget.show()
    sys.exit(app.exec())
